name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install
    - name: Build application
      run: npm run build
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
